import { Link, NavLink, useLocation } from "react-router-dom";
import FigmaFaq from "./FigmaFaq";
import { FigmaEventPrizes, FigmaContestantGrid } from "./FigmaEventStates";
import event, { figmaEventAssets } from "../../config/figmaEventScreens";
import "./figma-event-detail.css";
import "./figma-event-effects.css";
import "./figma-event-responsive.css";

const navItems = [["Home", "/"], ["Membership", "/Membership"], ["Manga", "/Manga"], ["Stories", "/Stories"], ["Gist", "/Gist"], ["Events", "/Events"]];
const tabs = ["Overview", "Prizes", "Rules", "Participants", "Brackets", "Matches"];

function ScreenHeader() { return <header className="figma-screen-header"><Link to="/"><img src={event.brandImage} alt="Ezzstar" /></Link><nav>{navItems.map(([label, to]) => <Link key={label} className={label === "Events" ? "selected" : ""} to={to}>{label}</Link>)}</nav><div className="header-actions">{Object.entries(figmaEventAssets.social).slice(0, 5).map(([name, src]) => <img key={name} src={src} alt={name} />)}<button aria-label="Search"><img src={figmaEventAssets.search} alt="" /></button><img className="header-profile" src={event.profileImage} alt="Profile" /></div></header>; }
function ScreenFooter() { return <footer className="figma-screen-footer"><img className="footer-brand" src={event.brandImage} alt="Ezzstar" /><nav><a href="#about">About Us</a><a href="#upload">Upload Manga</a><a href="#stories">Write Stories</a><a href="#thread">Create Thread</a><a href="#events">Create Events</a><a href="#wallet">Connect Wallet</a></nav><div className="footer-socials">{Object.entries(figmaEventAssets.social).slice(0, 5).map(([name, src]) => <img key={name} src={src} alt={name} />)}</div><div className="footer-legal"><a href="#privacy">Privacy Policy</a><a href="#terms">Terms of Use</a></div><p><b>© 2025 EZZSTAR</b> Decentralized Arts & Entertainment</p></footer>; }
function DetailTabs() { const { pathname } = useLocation(); const slug = pathname.split("/").at(-1); return <nav className="event-detail-tabs">{tabs.map((label) => { const route = label === "Overview" ? "../overview" : label === "Prizes" ? "../prizes" : label === "Participants" ? "../participants" : "../overview"; return <NavLink key={label} to={route} className={label.toLowerCase() === slug ? "active" : ""}>{label}</NavLink>; })}</nav>; }
function Hero() { const timer = event.countdown; return <section className="event-detail-hero" style={{ backgroundImage: `url(${event.heroImage})` }}><div className="hero-left-shade" /><div className="hero-bottom-shade" /><ScreenHeader /><div className="event-detail-hero-content"><div className="event-detail-tags"><span>{event.status}</span><span>{event.category}</span></div><h1>{event.title}</h1><div className="event-detail-actions"><button>Register</button><span>● Fee: {event.fee}</span><span>◉ {event.reward} {event.currency}</span></div></div><div className="event-detail-timer"><small>Tournament Starts-In</small><div><strong>{timer.days}</strong><span>days</span><strong>{String(timer.hours).padStart(2, "0")}</strong><span>hours</span><strong>{String(timer.mins).padStart(2, "0")}</strong><span>mins</span><strong>{String(timer.secs).padStart(2, "0")}</strong><span>secs</span></div></div></section>; }
function SideCard({ title, children, className = "" }) { return <section className={`event-detail-sidecard ${className}`}><h3>{title}</h3>{children}</section>; }
function Description() { const copy = event.description; return <section className="event-detail-body"><article className="event-detail-copy"><h2>Description</h2><div><p>{copy[0]}</p><p>{copy[1]}</p><p className="accent">{copy[2]}</p><p>{copy[3]}</p><h4>{copy[4]}</h4><p>{copy[5]}</p><h4>{copy[6]}</h4><p>{copy[7]}</p></div></article><aside className="event-detail-sidebar"><SideCard title="Upgrade your profile" className="host-card"><div className="host"><img src={event.hostedBy.avatar} alt={event.hostedBy.name} /><b>{event.hostedBy.name}</b></div></SideCard><SideCard title="Participants"><div className="participant-row"><img src={figmaEventAssets.users} alt="" /><b>32 Teams</b></div></SideCard><SideCard title="Platform"><div className="platform-icons">{figmaEventAssets.platforms.map((src, index) => <img src={src} alt={event.platform[index]} key={src} />)}</div></SideCard><SideCard title="Timeline" className="timeline-card"><div className="timeline"><i /><div><b>Tournament Starts From</b><span>12 April 2025</span><b>Tournament End Date</b><span>{event.timeline.endsAt}</span></div></div></SideCard></aside></section>; }
export default function FigmaEventDetail() { const { pathname } = useLocation(); const isPrizes = pathname.endsWith("/prizes"); const isParticipants = pathname.endsWith("/participants"); return <main className="figma-event-detail"><Hero /><DetailTabs />{isPrizes ? <FigmaEventPrizes event={event} /> : isParticipants ? <FigmaContestantGrid event={event} /> : <Description />}<FigmaFaq /><ScreenFooter /></main>; }
